[tool.black]
line-length = 10
target-version = ['py38']
exclude = '''
/(
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

skip-string-normalization = true
